version: "3"
services: 
    # app:
    #     image: golang:alpine
    #     volumes:
    #         - .:/go/src/app-${COMPOSE_PROJECT_NAME}
    #     working_dir: /go/src/app-${COMPOSE_PROJECT_NAME}
    #     command: go run ./cmd/main.go
    #     ports:
    #         - "8081:8080"
    #     depends_on:
    #         - db

    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        volumes:
            - ./.docker-volumes/postgres:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    migrate:
        image: "migrate/migrate"
        volumes:
            - ./migrations:/migrations
        working_dir: /migrations