version: "3"
services: 
    # app:
    #     image: golang:alpine
    #     volumes:
    #         - ..:/go/src/go-with-compose
    #     working_dir: /go/src/go-with-compose
    #     command: go run main.go
    #     ports:
    #         - "8080:8080"
    #     # depends_on:
    #     #     - db

    db:
        image: postgres
        environment: 
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=secret
        volumes:
            - ./_data/postgres/data:/var/lib/postgresql/data

    migrate:
        image: "migrate/migrate"
        volumes:
            - ../migrations:/migrations
        working_dir: /migrations