version: "3"
services: 
    # app:
    #     build: 
    #         context: ../
    #         dockerfile: ./docker/app/Dockerfile
    #     ports:
    #         - "8080:8080"

    postgres:
        image: "postgres:alpine"
        environment: 
            - POSTGRES_PASSWORD=secret
        volumes:
            - ./_data/postgres/data:/var/lib/postgresql/data

    # migrations:
    #     image: "migrate/migrate:latest"
    #     volumes:
    #         - ./migrations:/migrations
